import type { FC, PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Image from "next/image";
import { notFound } from "next/navigation";
import { Header } from "@/components";
import { useLocale, useMessages } from "next-intl";

import Providers from "../providers";

import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

type RootLayoutProps = {
  params: {
    locale: string;
  };
};

const RootLayout: FC<PropsWithChildren<RootLayoutProps>> = ({
  children,
  params,
}) => {
  const locale = useLocale();
  const messages = useMessages();

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale} className={poppins.className}>
      <body>
        <div id="root" className="absolute left-0 top-0 h-screen w-screen">
          <div className="absolute h-full w-full from-[#272770] via-[#090919] to-black from-10% to-55% via-35% bg-gradient-to-b">
            <Image src="/assets/images/bg-cover-mobile.png" fill alt="" />
          </div>
          <Header />
          <Providers locale={locale} messages={messages}>
            <main>{children}</main>
          </Providers>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
